### ISSUE TITLE
 remove faraday-http-cache gemspec version lock 

### ISSUE THREAD

**Issue by grantspeelman** [messagemedia/messages-ruby-sdk#18]
faraday-http-cache version in [message_media_messages.gemspec](https://github.com/messagemedia/messages-ruby-sdk/blob/e45d2aa16967a6e5e5046b6e8b8701824bbc48ac/message_media_messages.gemspec#L14) is preventing upgrading faraday past version 0.17.3.

if it can be updated to the following please

```ruby
  s.add_dependency('faraday-http-cache', '>= 1.2.2')
```

**Comment by grantspeelman** [comment]
@markbiegel is this possible please?

**Comment by s01ipsist** [comment]
Fixed by https://github.com/messagemedia/messages-ruby-sdk/commit/017c454e2b00c7170a4d9b3fb03c43645817179c
Thanks
